version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env.development
    depends_on:
      - db_dev

  db_dev:
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    volumes:
      - ./pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
